export const prompts = ["rabbit as marble statue",
"ninja cyborg as renaissance painting",
"scientists working on a time machine",
"planet saturn lithography",
"a man riding a shrimp motorcycle by salvador dali",
"zombies in london movie poster",
"erupting volcano surrounded by a sea",
"fluffy teddy bear on the moon",
"haunted mansion on a snowy hill by simon stalenhag",
"children book cover design illustration",
"a secret spy reading a newspaper in the 60's",
"indoor botanical garden low-angled light",
"trees on the moon by vincent van gogh",
"a fox playing in the forest by claude monet",
"photograph of a massive cthulhu in the distance kodachrome",
"ancient greek sculpture by ernst haeckel",
"a renaissance palace",
"renaissance portrait of a burmese cat",
"cat looking at sunset",
"a gigantic and brutalist tower",
"a pointillism drawing of a horse",
"surreal lovecraftian mouse",
"surreal bowl of fruit by rene magritte",
"art nouveau demon butterfly",
"art deco spaceship sketches",
"photograph of a cereal box from 1970s",
"birth of venus boticelli emergeing from a sandwich",
"realistic photo of a fight between a lion and a bear",
"magician fighting a final fantasy monster in a forest",
"giant whale floating in the sky water painting",
"portrait of a droid from irobot by edvard munch",
"ethereal moon hanging in a dark sky",
"anime girl wearing a cat hoodie holding an umbrella",
"a alien made out of slime by francis bacon",
"leon the professional painted by norman rockwell",
"mona lisa street art by banksy",
"microscopic bacteria by gustav klimt",
"a cat hermit crab animal mashup by caravaggio",
"ghosts and ghouls parade on main street by dali",
"cat playing basketball on the moon",
"abandoned factory room gloomy",
"close up of a person relaxing at a picnic by edward hopper",
"spirits over the horizon by studio ghibli",
"blue eyed woman wearing medieval armour",
"dragon flying over a medieval castle under a dark starred sky",
"a french bulldog on the beach",
"artistic depiction of an aztec pyramid",
"orange chair floating in space",
"nature landscape aerial view drone photography",
"flooded ancient tower at night by ralph mcquarrie",
"kanye west playing the piano in the middle of a garden",
"portrait shot of alien animals",
"cobra helmet heroic fantasy",
"universe in a grain of sand sci-fi",
"claymation movie screenshot at night",
"the sorcerer casting a fire ball heroic fantasy",
"front view of a japanese building facade with signs on it from Wes Anderson movie",
"ancient alien portal in the desert sundown",
"a kinetic sculpture of this solar system",
"solar eclipse in iceland psychedelic contre-jour",
"an anthropomorphic gangster mouse film noir illustration",
"cute owl wearing black biker jacket animal character illustration",
"full-body portrait of squirrel aristocrat",
"portrait of a knight stained glass",
"papan landscape by miyazaki",
"line art of a jazz band",
"psychedelic tarot card highly detailed",
"portrait of medusa michelangelo",
"black metal band logo",
"vampire portrait painting dorian grey romantic",
"illustration of a tropical island",
"impressionist painting of Las Vegas claude monet",
"black and white fashion photograph",
"a cinematic headshot portrait of a farmer",
"movie still of central park in the summer",
"flying spaghetti monster",
"a landscape painting of a french castle",
"bioluminescent monsters",
"rare bird in the jungle",
"you may say i'm a dreamer",
"nikolai tesla in his lab",
"spirit potion containing swirling glowing blue liquid",
"a bunny with a small head wearing a leather jacket",
"spaceport at the other end of the universe",
"japanese rural town",
"heavy fantasy armor",
"neon city cyberpunk",
"3d littlest pet shop",
"portrait of a beautiful android",
"nighttime in gotham city",
"an epic landscape view of a vast underwater metropolis",
"sea monster about to eat",
"go pro screenshot of the french revolutions",
"misty japanese bamboo forest",
"monk sitting at the top of a cliff",
"a path in an ancient forest",
"digital image of an imagination machine",
"knights in battle by alphonse mucha",
"a pigeon eating a pizza with its wings",
"an abandoned ship on the aral sea desert",
"lost city by atey ghailan"]

function between(min, max) {  
    return Math.floor(
      Math.random() * (max - min) + min
    )
  }

export function getRandomPrompt(){
    const p = between(0,prompts.length)
    return prompts[p]
}

